logging:
  level:
    org:
      springframework: INFO
    com:
      sap:
        olingo:
          jpa: INFO      
odata:
  jpa:
    punit_name: ${punit}
    root_packages: ${package}
server:
  port: ${port}
spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  flyway:
    enabled: true
    schemas:
    -  ${schema}
  servlet:
    multipart:
      enabled: false
