= How to make use of Annotations

OData provides the option to extend the metadata of your service to your own needs, by introducing 
annotations. Annotations can either be metadata annotations or instance annotations. 
Vocabularies describe by Terms the semantic of annotations, there structure and which OData artifact can be annotated. OData provides a set of 
https://github.com/oasis-tcs/odata-vocabularies/tree/main/vocabularies[Standardized Vocabularies],
but everyone is free to define own once. More insides into vocabularies and annotation can be found in the OData documentation in 
https://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#_Toc31358852[Part 1: Vocabulary Extensibility] and  
https://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_Annotations[Part 1: Annotations], as well as in the CSDL documentations
https://docs.oasis-open.org/odata/odata-csdl-json/v4.01/odata-csdl-json-v4.01.html#_Toc38466459[Json: Vocabulary and Annotation] and 
https://docs.oasis-open.org/odata/odata-csdl-xml/v4.01/odata-csdl-xml-v4.01.html#_Toc38530401[XML: Vocabulary and Annotation]

The JPA Processor supports, as of now, only metadata annotations. These are seen as static. That is they can not be changed between two requests. 
Three ways are provided to declare annotations, which will be explained in the following chapters.

== Use provided annotation EdmAnnotation

[#vocabulary]
=== Providing the vocabulary 

To make use of annotations the first step is to provide the corresponding vocabulary. A vocabularies are provided via an implementation of an extension of `JPAEdmMetadataPostProcessor`.
Method `provideReferences` has to be overridden. The method takes an instance of `IntermediateReferenceList`. The vocabulary has to be added to it:

[source,java]
----
public class MetadataPostProcessor extends JPAEdmMetadataPostProcessor {

  @Override
  public void provideReferences(IntermediateReferenceList referenceList) throws ODataJPAModelException {
    String uri = "http://docs.oasis-open.org/odata/odata-vocabularies/v4.0/vocabularies/Org.OData.Validation.V1.xml"; //<1>
    final String path = "annotations/Org.OData.Core.V1.xml"; //<2>
    IntermediateReferenceAccess vocabulary = referenceList.addReference(uri, path); //<3>
    vocabulary.addInclude("Org.OData.Core.V1", "Core"); //<4>
  }
  ...
}
----

<1> URI of the vocabulary. This can be taken, for standard vocabularies, from the vocabulary file. 
<2> Path to the vocabulary file within the resources of the project. The xml file can  be download from github: https://github.com/oasis-tcs/odata-vocabularies/blob/main/vocabularies/Org.OData.Core.V1.xml[OData Core] 
<3> A representation of the vocabulary is returned.
<4> Provide the namespace of the schema of the vocabulary used and the alias used within the metadata to reference the schema.

The JPA Processor takes this information to makes, on the one hand the terms of the vocabulary accessible for Olingo and on the other hand adds the reference to the vocabulary to the service document and the metadata:

[source,xml]
----
<edmx:Edmx xmlns:edmx="http://docs.oasis-open.org/odata/ns/edmx" Version="4.0">
	<edmx:Reference Uri="http://docs.oasis-open.org/odata/odata-vocabularies/v4.0/vocabularies/Org.OData.Validation.V1.xml"> <!--1-->
		<edmx:Include Namespace="Org.OData.Core.V1" Alias="Core"/>
	</edmx:Reference>
	<edmx:DataServices>
	...
	</edmx:DataServices>
</edmx:Edmx>	
----

<1> Vocabularies are part of the resource list within the metadata of a service. 

=== Annotate a property 

After we have provided the vocabulary, we can annotate e.g. a property. The following is example taken from the test data model from entity 
link:../../jpa/jpa-test/src/main/java/com/sap/olingo/jpa/processor/core/testmodel/BusinessPartner.java[BusinessPartner]. It indicates, that the location name is laguage dependent:

[source,java]
----
  @EdmAnnotation(term = "Core.IsLanguageDependent", //<1>
      constantExpression = @EdmAnnotation.ConstantExpression(type = ConstantExpressionType.Bool, value = "true")) //<2>
  @EdmDescriptionAssociation(languageAttribute = "key/language", descriptionAttribute = "name",
      valueAssignments = {
          @EdmDescriptionAssociation.valueAssignment(attribute = "key/codePublisher", value = "ISO"),
          @EdmDescriptionAssociation.valueAssignment(attribute = "key/codeID", value = "3166-1") })
  @OneToMany(fetch = FetchType.LAZY, cascade = CascadeType.ALL)
  @JoinColumn(name = "\"DivisionCode\"", referencedColumnName = "\"Country\"")
  private Collection<AdministrativeDivisionDescription> locationName;
----
<1> Name of the term the annotation is based on. The name a concatenation of the alias of the vocabulary and the name of the term.
<2> The annotation value. Only constant expressions are supported.

== Use JPAEdmMetadataPostProcessor

See <<vocabulary>>.

[NOTE]
====
This is the only way to annotate the Entity Container, as they do not have a java representation. 
====


== Use

