= Why are navigation count queries using greater or equal not supported? 

In OData queries a client can make use of the $count segment within a $filter expression to limit the items returned based on the exact count of related entities at collection-valued property.

A small example shall demonstrate this. The example uses an entity, https://github.com/SAP/olingo-jpa-processor-v4/blob/main/jpa/odata-jpa-test/src/main/java/com/sap/olingo/jpa/processor/core/testmodel/AdministrativeDivision.java[AdministrativeDivision], from the test model. AdministrativeDivisions is a hierarchy of subnational entities. 

To find all the divisions that have two sub-divisions, the following GET request can be used:
[source,url]
----
.../AdministrativeDivisions?$filter=Children/$count eq 2
----
This leads to the following SQL query:
[source,sql]
----
SELECT
	DISTINCT t0."Population",
	t0."Area",
	t0."DivisionCode",
	t0."ParentCodeID",
	t0."AlternativeCode",
	t0."CountryISOCode",
	t0."CodePublisher",
	t0."ParentDivisionCode",
	t0."CodeID"
	FROM "OLINGO"."AdministrativeDivision" t0
	WHERE (EXISTS ( 
		SELECT t1."CodePublisher"
			FROM "OLINGO"."AdministrativeDivision" t1
			WHERE (((t1."CodePublisher" = t0."CodePublisher")
			AND (t1."ParentCodeID" = t0."CodeID"))
			AND (t1."ParentDivisionCode" = t0."DivisionCode"))
			GROUP BY t1."CodePublisher", t1."ParentCodeID", t1."ParentDivisionCode"
			HAVING (COUNT(t1."DivisionCode") = 2)))
----
To restrict the rows returned to those having 2 children a sub-query. The restriction is done by a HAVING clause. Unfortunately this construct is not able to compare with 0. E.g. to find all leaves, lowest level of divisions, the following GET request can be used:
[source,url]
----
.../AdministrativeDivisions?$filter=Children/$count eq 0
----
in case this would result in the following SQL 
[source,sql]
----
SELECT
	DISTINCT t0."Population",
	t0."Area",
	t0."DivisionCode",
	t0."ParentCodeID",
	t0."AlternativeCode",
	t0."CountryISOCode",
	t0."CodePublisher",
	t0."ParentDivisionCode",
	t0."CodeID"
	FROM "OLINGO"."AdministrativeDivision" t0
	WHERE (EXISTS ( 
		SELECT t1."CodePublisher"
			FROM "OLINGO"."AdministrativeDivision" t1
			WHERE (((t1."CodePublisher" = t0."CodePublisher")
			AND (t1."ParentCodeID" = t0."CodeID"))
			AND (t1."ParentDivisionCode" = t0."DivisionCode"))
			GROUP BY t1."CodePublisher", t1."ParentCodeID", t1."ParentDivisionCode"
			HAVING (COUNT(t1."DivisionCode") = 0)))
----
The query would not restrict at all. Instead of this  NOT EXIST comparing not equal zero is used:
[source,sql]
----
SELECT
	DISTINCT t0."Population",
	t0."Area",
	t0."DivisionCode",
	t0."ParentCodeID",
	t0."AlternativeCode",
	t0."CountryISOCode",
	t0."CodePublisher",
	t0."ParentDivisionCode",
	t0."CodeID"
	FROM "OLINGO"."AdministrativeDivision" t0
	WHERE NOT (EXISTS ( 
		SELECT t1."CodePublisher"
			FROM "OLINGO"."AdministrativeDivision" t1
			WHERE (((t1."CodePublisher" = t0."CodePublisher")
			AND (t1."ParentCodeID" = t0."CodeID"))
			AND (t1."ParentDivisionCode" = t0."DivisionCode"))
			GROUP BY t1."CodePublisher", t1."ParentCodeID", t1."ParentDivisionCode"
			HAVING (COUNT(t1."DivisionCode") <> 0)))
----
In case a client requests $count greater or equal 0, it would mean to create a sub-query with NOT EXISTS and a sub-query with EXISTS. This does not make sense, as in fact such a request does not restrict the result at all.