name: Build OData JPA Processor
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build without criteria builder
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK to 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'
          cache: maven
      - name: 1. Build JPA
        run: cd ./jpa && mvn clean install -Dmaven.test.skip    
      - name: 2. Build processor without criteria builder
        run: cd ./jpa && mvn --projects odata-jpa-processor -Pwo-extension clean install         
